# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coordinate_l1 <- function(x0, xty, xtx, pen, thr, max_iter) {
    .Call('_spring_coordinate_l1', PACKAGE = 'spring', x0, xty, xtx, pen, thr, max_iter)
}

